# Header
menu:
  home: /
  archives: /archives
rss: 

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 10

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- archive
# - category
# - tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

language:
- zh-CN
- en

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
gauges_analytics:
favicon: /favicon.ico
weibo: Junior_99
wechat: ZXS-WeChat
qq: 546990481
mail: zh_cn2008@hotmail.com
